{{- $defaults := . -}}

{{- range $index, $value := .Values.microservices }}
{{- $_ := set $value "nameOverride" $index }}
{{- $microservice := dict "Values" $value }}
{{- $defaultsCopy := $defaults | deepCopy }}
{{- with mergeOverwrite $defaultsCopy $microservice }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "v2.fullname" . }}-deployment
  labels:
    {{- include "v2.labels" . | nindent 4 }}
spec:
  replicas: {{ $value.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ include "v2.fullname" . }}
      {{- include "v2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "v2.fullname" . }}
        {{- include "v2.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      {{- if $value.migrations }}
        - name: {{ $value.migrations.container.name }}
          image: {{ $value.migrations.image.name }}:{{ $value.migrations.image.tag }}
          imagePullPolicy: Never
          command: [ "db-migrate", "up", "--config", "./database.json", "--env", "prod" ]
          env:
            - name: DB_SERVICE_NAME
              value: {{ include "v2.releaseName" . }}-db-service
            - name: KUBERNETES_CLUSTER_DOMAIN
              value: {{ quote .Values.kubernetesClusterDomain }}
          envFrom:
            - configMapRef:
                name: {{ include "v2.releaseName" . }}-db-config
            - secretRef:
                name: {{ include "v2.releaseName" . }}-db-secret
      {{- end }}
      containers:
        - name: {{ $value.container.name }}
          image: {{ $value.image.name }}:{{ $value.image.tag }}
          imagePullPolicy: Never
          ports:
          {{- range $value.service.ports }}
            - containerPort: {{ .containerPort }}
              name: {{ .name }}
          {{- end}}
            - env:
                - name: PRODUCT_CATALOGUE_SERVICE_NAME
                  value: {{ include "v2.releaseName" . }}-product-catalogue-service-service
                - name: ORDER_SERVICE_NAME
                  value: {{ include "v2.releaseName" . }}-order-service-service
                - name: PROMO_SERVICE_NAME
                  value: {{ include "v2.releaseName" . }}-promo-service-service
                - name: DB_SERVICE_NAME
                  value: {{ include "v2.releaseName" . }}-db-service
                - name: KUBERNETES_CLUSTER_DOMAIN
                  value: {{ quote .Values.kubernetesClusterDomain }}
{{ end }}
{{ end }}