apiVersion: v1
kind: Secret
metadata:
  name: {{ include "v2.fullname" . }}-db-secret
  labels:
  {{- include "v2.labels" . | nindent 4 }}
data:
  MYSQL_PASSWORD: {{ required "dbSecret.mysqlPassword is required" .Values.dbSecret.mysqlPassword
    | b64enc | quote }}
  MYSQL_ROOT_PASSWORD: {{ required "dbSecret.mysqlRootPassword is required" .Values.dbSecret.mysqlRootPassword
    | b64enc | quote }}
  MYSQL_USER: {{ required "dbSecret.mysqlUser is required" .Values.dbSecret.mysqlUser
    | b64enc | quote }}
type: Opaque