apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "v2.fullname" . }}-db-config
  labels:
  {{- include "v2.labels" . | nindent 4 }}
data:
  MYSQL_DATABASE: {{ .Values.dbConfig.mysqlDatabase | quote }}