apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "v2.fullname" . }}-client-ingress
  labels:
  {{- include "v2.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: '{{ include "v2.fullname" . }}-client-service'
                port:
                  number: 3000
            path: /
            pathType: 'Prefix'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "v2.fullname" . }}-order-service-ingress
  labels:
  {{- include "v2.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: '{{ include "v2.fullname" . }}-order-service-service'
                port:
                  number: 3002
            path: /api/order-service
            pathType: 'Prefix'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "v2.fullname" . }}-product-catalogue-service-ingress
  labels:
  {{- include "v2.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: '{{ include "v2.fullname" . }}-product-catalogue-service-service'
                port:
                  number: 3001
            path: /api/product-catalog-service
            pathType: 'Prefix'
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "v2.fullname" . }}-promo-service-ingress
  labels:
  {{- include "v2.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: 'nginx'
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: '{{ include "v2.fullname" . }}-promo-service-service'
                port:
                  number: 3003
            path: /api/promo-service
            pathType: 'Prefix'