apiVersion: v1
kind: Service
metadata:
  name: {{ include "v2.fullname" . }}-client-service
  labels:
  {{- include "v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.clientService.type }}
  selector:
    app: {{ include "v2.fullname" . }}-client
  {{- include "v2.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.clientService.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "v2.fullname" . }}-db-service
  labels:
  {{- include "v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbService.type }}
  selector:
    app: {{ include "v2.fullname" . }}-db
  {{- include "v2.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.dbService.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "v2.fullname" . }}-order-service-service
  labels:
  {{- include "v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.orderServiceService.type }}
  selector:
    app: {{ include "v2.fullname" . }}-order-service
  {{- include "v2.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.orderServiceService.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "v2.fullname" . }}-product-catalogue-service-service
  labels:
  {{- include "v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.productCatalogueServiceService.type }}
  selector:
    app: {{ include "v2.fullname" . }}-product-catalogue-service
  {{- include "v2.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.productCatalogueServiceService.ports | toYaml | nindent 2 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "v2.fullname" . }}-promo-service-service
  labels:
  {{- include "v2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.promoServiceService.type }}
  selector:
    app: {{ include "v2.fullname" . }}-promo-service
  {{- include "v2.selectorLabels" . | nindent 4 }}
  ports:
 {{- .Values.promoServiceService.ports | toYaml | nindent 2 }}