apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: cos-db-test
          image: cos-db:0.0.5
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/db/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
