apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
  labels:
    app.kubernetes.io/managed-by: helm
data:
  MYSQL_DATABASE: '{{ .Values.database.mysqlDatabase }}'