apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  labels:
    app.kubernetes.io/managed-by: helm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
          ports:
            - containerPort: {{.Values.service.ports.containerPort}}
          volumeMounts:
            - name: {{ .Release.Name }}-{{ .Chart.Name }}-storage
              mountPath: /var/lib/db/data
      volumes:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
