apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
  labels:
    app.kubernetes.io/managed-by: helm
data:
  MYSQL_ROOT_PASSWORD: '{{.Values.database.secret.mySQLRootPassword}}'
  MYSQL_USER: '{{.Values.database.secret.mySQLUser}}'
  MYSQL_PASSWORD: '{{.Values.database.secret.mySQLPassword}}'