apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      initContainers:
        - name: cos-order-service-migrations-run
          image: cos-order-service-migrations:latest
          imagePullPolicy: Never
          command: [ "db-migrate", "up", "--config", "./database.json", "--env", "prod" ]
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          env:
            - name: DB_SERVICE_NAME
              value: db-service
      containers:
        - name: cos-order-service-test
          image: cos-order-service:latest
          imagePullPolicy: Never
          env:
            - name: PRODUCT_CATALOGUE_SERVICE_NAME
              value: product-catalogue-service-service
            - name: ORDER_SERVICE_NAME
              value: order-service-service
            - name: PROMO_SERVICE_NAME
              value: promo-service-service
            - name: DB_SERVICE_NAME
              value: db-service
          ports:
            - containerPort: 3002